<a href="https://colab.research.google.com/github/fray517/ml/blob/main/Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from traitlets import link
import yfinance as yf
# импорт данных
list_tickers = ["AAPL", "NFLX", "TSLA"]
database = yf.download(list_tickers)
# берем только скорректированную цену акций
database = database["Adj Close"]
# удаляем пропущенные значения
data = database.dropna().pct_change(1).dropna()
data

[*********************100%***********************]  3 of 3 completed

                AAPL      NFLX      TSLA
Date
2010-06-30 -0.018113 -0.034908 -0.002511
2010-07-01 -0.012126  0.009296 -0.078473
2010-07-02 -0.006198 -0.023527 -0.125683
2010-07-06  0.006843  0.001774 -0.160937
2010-07-07  0.040382  0.104596 -0.019243
...              ...       ...       ...
2023-03-24  0.008306  0.025034 -0.009416
2023-03-27 -0.012293 -0.002223  0.007353
2023-03-28 -0.003980 -0.012635 -0.013659
2023-03-29  0.019791  0.026304  0.024790
2023-03-30  0.009890  0.019275  0.007221

[3210 rows x 3 columns]

In [ ]:
import numpy as np
def MV_criterion(weights, data):
   """Выходные данные : критерий оптимизации портфеля
      Входные данные :  - weight (массив ndarray numpy) 
      вес для портфеля
      - data : массив ndarray numpy 
      возврат акций"""
   # параметры
   Lambda = 3
   W = 1
   Wbar = 1 + 0.25 / 10.0
   # Вычисляем возврат портфеля
   portfolio_return = np.multiply(data, np.transponse(weights))
   portfolio_return = portfolio_return.sum(axis=1)